# Generated by Django 2.1 on 2018-08-30 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BasicInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Age', models.CharField(max_length=200)),
                ('Sex', models.CharField(max_length=20)),
                ('DOB', models.DateTimeField(verbose_name='Date of Birth')),
                ('Email', models.EmailField(max_length=200)),
                ('Phone', models.CharField(max_length=200)),
                ('Address', models.CharField(max_length=2500)),
                ('Language', models.CharField(max_length=1500)),
            ],
        ),
        migrations.CreateModel(
            name='EducationInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Period', models.CharField(max_length=200)),
                ('DegreeLevel', models.CharField(max_length=200)),
                ('DegreeName', models.CharField(max_length=200)),
                ('UniversityName', models.CharField(max_length=200)),
                ('Details', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='ExperienceInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Period', models.CharField(max_length=200)),
                ('CompanyName', models.CharField(max_length=200)),
                ('Position', models.CharField(max_length=200)),
                ('Details', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='MenuList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MenuName', models.CharField(max_length=200)),
                ('MenuText', models.CharField(max_length=200)),
                ('IsActive', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='PortfolioCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='PortfolioInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('ImgLoc', models.CharField(max_length=500)),
                ('PortfolioCategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.PortfolioCategory')),
            ],
        ),
        migrations.CreateModel(
            name='ProfileInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Title', models.CharField(max_length=2000)),
                ('ImgLoc', models.CharField(max_length=500)),
                ('CVLink', models.CharField(max_length=500)),
                ('Goals', models.CharField(max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='RefrenceInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RefreeName', models.CharField(max_length=200)),
                ('RefreePost', models.CharField(max_length=200)),
                ('RefreeCompany', models.CharField(max_length=500)),
                ('Details', models.CharField(max_length=2000)),
                ('ProfileInfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.ProfileInfo')),
            ],
        ),
        migrations.CreateModel(
            name='SkillInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SkillName', models.CharField(max_length=500)),
                ('SkillPercentage', models.CharField(max_length=100)),
                ('ProfileInfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.ProfileInfo')),
            ],
        ),
        migrations.CreateModel(
            name='SocialSiteInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Link', models.CharField(max_length=500)),
                ('ProfileInfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.ProfileInfo')),
            ],
        ),
        migrations.AddField(
            model_name='portfolioinfo',
            name='ProfileInfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.ProfileInfo'),
        ),
        migrations.AddField(
            model_name='experienceinfo',
            name='ProfileInfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.ProfileInfo'),
        ),
        migrations.AddField(
            model_name='educationinfo',
            name='ProfileInfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.ProfileInfo'),
        ),
        migrations.AddField(
            model_name='basicinfo',
            name='ProfileInfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.ProfileInfo'),
        ),
    ]
